### PR TITLE
Handle wallet events

### LINKED ISSUE #4: Switching account in Metamask doesn't change it in dApp
Steps to reproduce:
1. Open https://wrose.oasis.io, click Connect Wallet
2. Metamask pops up, select an account
3. Account address is shown in the top-right corner of dApp (0x.... Sapphire Testnet)
4. Open Metamask again, connect and select a different account
5. The old account address is still shown in the top-right corner.

Expected behavior:
When the account is switched in Metamask, it should also be updated in the dApp.

### PR DESCRIPTION
**Pull request by lubej**
Handles following wallet events:
- `accountsChanged`
- `chainChanged`
- `connect` & `disconnect`

Closes https://github.com/oasisprotocol/dapp-wrose/issues/4

### CODE REVIEW

File: src/providers/Web3Provider.tsx [hunk 1]
```diff
@@ -60,35 +60,96 @@ export const Web3ContextProvider: FC<PropsWithChildren> = ({ children }) => {
...
+    ethProvider.on('chainChanged', _chainChanged)
+    ethProvider.on('connect', _connect)
+    ethProvider.on('disconnect', _disconnect)
+  }
+
+  const _removeEventListeners = (ethProvider = window.ethereum) => {
+    ethProvider.off('accountsChanged', _accountsChanged)
+    ethProvider.off('chainChanged', _chainChanged)
+    ethProvider.off('connect', _connect)
+    ethProvider.off('disconnect', _disconnect)
```
Comment (lukaw3d) [inline src/providers/Web3Provider.tsx:131]: This doesn't work, referenced functions aren't the old instance:
- disconnect all accounts from wrose
- add console.log to _accountsChanged and _init
- connect an account + change account
- see 1 '_accountsChanged' printed
- disconnect all accounts from wrose
- see 1 '_init' printed
- connect an account + change account
- see 2 '_accountsChanged' printed
- disconnect all accounts from wrose
- see 1 '_init' printed
- connect an account + change account
- see 3 '_accountsChanged' printed

File: src/providers/Web3Provider.tsx [hunk 2]
```diff
@@ -121,9 +182,9 @@ export const Web3ContextProvider: FC<PropsWithChildren> = ({ children }) => {
...
 
   const isMetaMaskInstalled = async () => {
-    const provider = await detectEthereumProvider();
+    const provider = await detectEthereumProvider()
 
-    return !!window.ethereum && provider === window.ethereum;
+    return !!window.ethereum && provider === window.ethereum
   }
 
   const connectWallet = async () => {
```
Comment (lukaw3d) [inline src/providers/Web3Provider.tsx:195]:
```ts
const [account] = await window.ethereum.request?.({ method: 'eth_requestAccounts' })`
```

This looks wrong.
- if window.ethereum is missing, it will throw `Cannot read properties of undefined`
- if window.ethereum.request is missing, it will throw `undefined is not iterable`

I'd expect
```tsx
    const accounts = await window.ethereum?.request?.({ method: 'eth_requestAccounts' })

    if (!accounts) {
      throw new Error('[Web3Context] Request account failed!')
    }

    await _init(accounts[0])
```

File: src/providers/Web3Provider.tsx (hunk 1 above)
Comment (lubej) [reply src/providers/Web3Provider.tsx:131]: True, thanks for catching this 👍

File: src/providers/Web3Provider.tsx (hunk 2 above)
Comment (lubej) [reply src/providers/Web3Provider.tsx:195]: Sure, `isMetaMaskInstalled` method was intended to check for that case, if `window.ethereum` wouldn't be defined, or would not be a "correct" wallet object. But since I added the option to skip, it is a valid point 👍

File: src/providers/Web3Provider.tsx [hunk 3]
```diff
@@ -60,36 +60,101 @@ export const Web3ContextProvider: FC<PropsWithChildren> = ({ children }) => {
...
         sapphire.SapphireAnnex
 
       const network = await sapphireEthProvider.getNetwork()
 
-      if (!(network.chainId in NETWORKS)) {
-        return Promise.reject(new UnknownNetworkError('Unknown network!'))
+      try {
+        await _setNetworkSpecificVars(network.chainId, sapphireEthProvider)
+      } catch (ex) {
+        return Promise.reject(ex)
```
Comment (lukaw3d) [inline src/providers/Web3Provider.tsx:147]: This is odd. Is it not the same as `throw ex`. And the same as removing `try catch` all together

File: src/providers/Web3Provider.tsx [hunk 4]
```diff
@@ -60,36 +60,101 @@ export const Web3ContextProvider: FC<PropsWithChildren> = ({ children }) => {
...
+      const ethProvider = new ethers.providers.Web3Provider(window.ethereum!)
       const sapphireEthProvider = sapphire.wrap(ethProvider) as ethers.providers.Web3Provider &
         sapphire.SapphireAnnex
 
       const network = await sapphireEthProvider.getNetwork()
 
-      if (!(network.chainId in NETWORKS)) {
-        return Promise.reject(new UnknownNetworkError('Unknown network!'))
+      try {
+        await _setNetworkSpecificVars(network.chainId, sapphireEthProvider)
```
Comment (lukaw3d) [inline src/providers/Web3Provider.tsx]: Needless await

**Review by lukaw3d — APPROVED** [review]

File: src/providers/Web3Provider.tsx (hunk 3 above)
Comment (lubej) [reply src/providers/Web3Provider.tsx:147]: So idea behind this was, that `_setNetworkSpecificVars` throws specific `UnknownNetworkError` which I want to propagate to the caller. The whole `_init` is inside another try-catch block that rethrows `Unable to initialize providers` generic message. So either I rethrow the thrown error in `_init`, or return the Promise with the error(The way it is now).

Comment (lukaw3d) [reply src/providers/Web3Provider.tsx:147]: Ah. Ew. Just add `if (ex instanceof UnknownNetworkError) throw ex` to the upper catch
